app/models.py
# !/usr/bin/env python
# coding=utf-8

__date__ = '2016/4/12'
__author__ = 'chuan.li'
from app import db, login_manager
from flask_login import UserMixin, AnonymousUserMixin
from datetime import datetime
from markdown import markdown


class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(32))
    users = db.relationship('User', backref='role')

    @staticmethod
    def seed():
        db.session.add_all(map(lambda r: Role(name=r), ['Guests', 'Administrators']))
        db.session.commit()


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64))
    email = db.Column(db.String(64))
    password = db.Column(db.String(64))
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))

    posts = db.relationship('Post', backref='author')
    comments = db.relationship('Comment', backref='author')

    locale = db.Column(db.String(32), default='zh')

    @staticmethod
    def on_created(target, value, oldvalue, initiator):
        target.role = Role.query.filter_by(name='Guests').first()


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class AnonymousUser(AnonymousUserMixin):
    @property
    def locale(self):
        return 'zh'

    def is_administrator(self):
        return False


login_manager.anonymous_user = AnonymousUser

db.event.listen(User.name, 'set', User.on_created)


class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(64))
    body = db.Column(db.Text)
    body_html = db.Column(db.Text)
    created = db.Column(db.DateTime, index=True, default=datetime.utcnow)

    comments = db.relationship('Comment', backref='post')
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    @staticmethod
    def on_body_changed(target, value, oldvalue, initiator):
        if value is None or (value is ''):
            target.body_html = ''
        else:
            target.body_html = markdown(value)


db.event.listen(Post.body, 'set', Post.on_body_changed)


class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    post_id = db.Column(db.Integer, db.ForeignKey('posts.id'))
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))

app/main/forms.py
#!/usr/bin/env python
# coding=utf-8

__date__ = '2016/5/16'
__author__ = 'chuan.li'

from flask_wtf import Form
from wtforms import SubmitField, StringField
from wtforms.validators import DataRequired, Length
from flask_pagedown.fields import PageDownField
from flask_babel import lazy_gettext as _


class PostForm(Form):
    title = StringField(label=_('标题'), validators=[DataRequired()])
    body = PageDownField(label=_('正文'), validators=[DataRequired()])
    submit = SubmitField(label=_('发表'))


class CommentForm(Form):
    body = PageDownField(label=_('评论'), validators=[DataRequired()])
    verification_code = StringField(_('验证码'), validators=[DataRequired(), Length(4, 4, message=_('填写4位验证码！'))])
    submit = SubmitField(label=_('发表'))

app/__init__.py
#!/usr/bin/env python
# coding=utf-8

__date__ = '2016/4/12'
__author__ = 'chuan.li'

import sys
from flask import Flask,make_response
from flask_bootstrap import Bootstrap
from flask_nav.elements import *
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager, current_user
from datetime import timedelta
from flask_pagedown import PageDown
from flask_gravatar import Gravatar
from flask_babel import Babel, lazy_gettext

reload(sys)
sys.setdefaultencoding("utf-8")

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
login_manager.login_message = lazy_gettext('登陆后方可访问该页面！')
pagedown = PageDown()
babel = Babel()


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'THIS IS JUST A TEST WEBPAGE !'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://root:R0boo@Sip$@127.0.0.1/maizi'
    app.config['BABEL_DEFAULT_LOCALE'] = 'en'
    app.config['SQLALCHEMY_COMMIT_ON_TEARDOWN'] = True
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True
    from flask.json import JSONEncoder

    class CustomJSONEncoder(JSONEncoder):
        """This class adds support for lazy translation texts to Flask's
        JSON encoder. This is necessary when flashing translated texts."""

        def default(self, obj):
            from speaklater import is_lazy_string
            if is_lazy_string(obj):
                try:
                    return unicode(obj)  # python 2
                except NameError:
                    return str(obj)  # python 3
            return super(CustomJSONEncoder, self).default(obj)

    app.json_encoder = CustomJSONEncoder

    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    pagedown.init_app(app)
    Gravatar(app, size=64)
    babel.init_app(app)

    from auth import auth as auth_blueprint
    from main import main as main_blueprint
    app.register_blueprint(auth_blueprint)
    app.register_blueprint(main_blueprint)

    app.permanent_session_lifetime = timedelta(minutes=5)

    @app.template_test('current_link')
    def is_current_link(link):
        return link == request.path

    @babel.localeselector
    def get_locale():
        return current_user.locale

    return app

app/main/__init__.py
#!/usr/bin/env python
# coding=utf-8

from flask import Blueprint

main = Blueprint('main', __name__)
import views,forms

app/main/views.py
#!/usr/bin/env python
# coding=utf-8

__date__ = '2016/4/12'
__author__ = 'chuan.li'

from flask import render_template, redirect, url_for, request, session, make_response,flash
from . import main
from flask_login import login_required, current_user
from app.models import Post, Comment
from forms import CommentForm, PostForm
from app import db
from flask_babel import lazy_gettext, gettext as _

try:
    import cStringIO as StringIO
except:
    import StringIO


@main.route('/')
def index():
    page_index = request.args.get('page', 1, type=int)
    query = Post.query.order_by(Post.created.desc())
    pagination = query.paginate(page_index, per_page=10, error_out=False)
    posts = pagination.items
    return render_template('index.html', title=lazy_gettext('欢迎来到我的博客'), posts=posts, pagination=pagination)


@main.route('/about')
def about():
    return 'about'


@main.route('/project')
def project():
    return 'Project!'


@main.route('/posts/<int:id>', methods=['POST', 'GET'])
def post(id):
    # 详情页
    post = Post.query.get_or_404(id)
    form = CommentForm()
    if form.validate_on_submit():
        if 'sec_code' in session and session['sec_code'] != form.verification_code.data:
            flash(lazy_gettext('验证码错误，请刷新！'))
            return  render_template('posts/detail.html', title=post.title, form=form, post=post)
        else:
            comment = Comment(author=current_user, body=form.body.data, post=post)
            db.session.add(comment)
            db.session.commit()
    return render_template('posts/detail.html', title=post.title, form=form, post=post)


@main.route('/sec/code')
def security_code():
    from sec_code import create_validate_code
    image, strs = create_validate_code()
    buf = StringIO.StringIO()
    image.save(buf, 'JPEG', quality=60)
    session['sec_code'] = strs
    print session['sec_code']
    buf_str = buf.getvalue()
    response = make_response(buf_str)
    response.headers['Content-Type'] = 'image/jpeg'
    return response


@main.route('/edit', methods=['GET', 'POST'])
@main.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id=0):
    form = PostForm()
    if id == 0:
        post = Post(author_id=current_user.id)
    else:
        post = Post.query.get_or_404(id)
    if form.validate_on_submit():
        post.body = form.body.data
        post.title = form.title.data
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('.post', id=post.id))

    title = _('添加新文章')
    if id > 0:
        title = _('编辑 - %(title)', title=post.title)
    return render_template('posts/edit.html', title=title, form=form, post=post)


@main.errorhandler(404)
def page_not_found(e):
    return '404', 404

# @main.add_app_template_test('current_link')
# def is_current_link(link):
#     return link == request.path

app/templates/base.html
{% extends 'bootstrap/base.html' %}
{% block head %}


    {% block metas %}
        {{ super() }}
        <meta charset="UTF-8">
    {% endblock metas %}
    {#    {% include ['includes/_head.html', 'includes/_metas.html'] %}#}
    {% block styles %}
        <style type="text/css">
            a:link {
                color: #2b47ff
            }

            a:visited {
                color: #5bddff
            }

            a:hover {
                color: #FF00FF
            }

            a:active {
                color: #0000FF
            }
        </style>
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
        <link rel="stylesheet" href="{{ url_for('static',filename='bootstrap.min.css') }}">
        {#        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.6/slate/bootstrap.min.css">#}
    {% endblock styles %}

    <title>{% block title %}{{ title }}{% endblock title %}</title>

{% endblock head %}

{% block body %}

    {% block navbar %}
        {#        {{ nav.top.render() }}#}
        {% include 'includes/_navbar.html' %}
    {% endblock %}

    {% block header %}
        <header>
            <div class="container">
                <div class="page-header">
                    <h2>{{ title }}</h2>
                </div>
            </div>
        </header>
    {% endblock header %}

    {% block content %}
    {% endblock content %}

    {% block page_body %}
    {% endblock page_body %}

    {% block scripts %}
        {{ super() }}
        <script src="{{ url_for('static',filename='bootstrap.min.js') }}"></script>
        <script src="{{ url_for('static',filename='jquery.min.js') }}"></script>
    {% endblock scripts %}

    <footer>
        <div class="navbar navbar-default" align="center">
            {% block footer %}
                &copy; Copyright 2016 by <a href="http://www.payegis.com.cn" target="_blank">PayEgis</a>
                <sup>&reg;</sup>.
            {% endblock footer %}
        </div>
    </footer>

{% endblock body %}

app/templates/basemodel.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}</title>
    {% endblock %}
</head>
<body>
<header>{% block header %}{% endblock %}</header>
<div >{% block content %}{% endblock %}</div>
    {% block footer %}
        <footer>
    &copy;Copyright 2016 by <a href="http://www.payegis.com.cn" target="_blank">Payegis</a>.
        </footer>
    {% endblock %}
</body>
</html>

app/templates/includes/_head.html
<meta charset="UTF-8">
<link href="{{ url_for('static',filename='site.css') }}" rel="stylesheet">
<title>{% block title %}{% endblock %}</title>

app/templates/includes/_navbar.html
<nav class="navbar navbar-default navbar-static-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button aria-controls="navbar"
                    aria-expanded="false"
                    class="navbar-toggle collapsed"
                    data-target="#7bc75dbef69e41ff2452de70079c8ece1320ea7c"
                    data-toggle="collapse" type="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <span class="navbar-brand">{{ _("Flask入门") }}</span>
        </div>
        <div class="navbar-collapse collapse"
             id="7bc75dbef69e41ff2452de70079c8ece1320ea7c">
            <ul class="nav navbar-nav">
                <li {% if url_for('main.index') is current_link %}class="active"{% endif %}>
                    <a href="{{ url_for('main.index') }}" title={{ _("主页") }}>{{ _("主页") }}</a>
                </li>
                <li {% if url_for('main.about') is current_link %}class="active"{% endif %}>
                    <a href="{{ url_for('main.about') }}" title={{ _("关于") }} >{{ _("关于") }}</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated  %}
                    <li><a href="#">{{ current_user.name }}</a></li>
                    <li><a href="{{ url_for('auth.logout') }}">{{ _("退出") }}</a></li>
                {% else %}
                    <li><a href="{{ url_for('auth.login') }}">{{ _("登录") }}</a></li>
                    <li><a href="{{ url_for('auth.register') }}">{{ _("注册") }}</a></li>
                {% endif %}
{#                {{ current_user.is_authenticated }}#}
            </ul>
        </div>
    </div>
</nav>

app/templates/index.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% block page_body %}
    <div class="container">
        <a href="{{ url_for('main.edit') }}" class="btn btn-primary">{{ _("发表新文章") }}</a>
    </div>
    <div class="container">
        {% for post in posts %}
            <h2><a href="{{ url_for('main.post', id = post.id) }}">{{ post.title }}</a></h2>
            <div>
                {{ post.body_html|safe }}
            </div>
        {% endfor %}
        {{ render_pagination(pagination) }}
    </div>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
    <div class="container">
{#                    <form method="post">#}
{#                        <div>{{ form.hidden_tag() }}</div>#}
{#                        <div>{{ form.username.label }}</div>#}
{#                        <div>{{ form.username }}</div>#}
{#                        <div>{{ form.password.label }}</div>#}
{#                        <div>{{ form.password }}</div>#}
{#                        <div>{{ form.submit(class='btn btn-primary') }}</div>#}
{#                    </form>#}
        {% for msg  in get_flashed_messages() %}
            <div class='alert-danger'>{{ msg }}</div>
        {% endfor %}
        {{ wtf.quick_form(form) }}
    </div>
{% endblock %}

app/templates/posts/detail.html
{% extends 'base.html' %}
{% block page_body %}
    <div class="container">
        <span>{{ _("作者") }}：{{ post.author.name }} </span><span>{{ _("发表日期") }}：{{ post.created }}</span>
        <hr>
        <div>
            {{ post.body_html|safe }}
        </div>
        <form method="post" class="form" role="form">
            {{ form.hidden_tag() }}


            <div class="form-group required">
                {{ form.body.label(class="control-label") }}
                {{ form.body(class="form-control flask-pagedown-input" ,required=True) }}
            </div>

            {% if form.errors.verification_code %}
                <div class="form-group has-error required" style="margin-top: 10px;">
                    {{ form.verification_code.label(class="control-label") |safe }}
                    {{ form.verification_code(size=4,maxlength=4) }}
                    <label class="control-label">
                        <img src="{{ url_for('main.security_code') }}" id="sec_code"/>&nbsp;
                        <small>{{ _('看不清？点击') }}<a href="javascript:void(0)"
                                                   onclick="UpdateCode()">刷新</a>！
                        </small>
                    </label>
                    {% for error in form.errors.verification_code %}
                        <p class="help-block">{{ error }}</p>
                    {% endfor %}
                </div>
            {% else %}
                <div class="form-group required" style="margin-top: 10px;">
                    {{ form.verification_code.label(class="control-label") |safe }}
                    {{ form.verification_code(size=4,maxlength=4) }}
                    <label class="control-label">
                        <img src="{{ url_for('main.security_code') }}" id="sec_code"/>&nbsp;
                        <small>{{ _('看不清？点击') }}<a href="javascript:void(0)"
                                                   onclick="UpdateCode()">刷新</a>！
                        </small>
                    </label>
                </div>
            {% endif %}

            {% for message in get_flashed_messages() %}
                <div class="alert-danger form-group required">{{ message }}</div>
            {% endfor %}

            <div class="form-group required">
                {{ form.submit(class="btn btn-primary submit" ,type='submit') }}
            </div>

        </form>
        {% for comment in post.comments | sort(attribute='created',reverse=True) %}
            <div class="media">
                <div class="media-left">
                    <a href="#">
                        <img class="media-object img-circle" src="{{ comment.author.email | gravatar }}">
                    </a>
                </div>
                <div class="media-body">
                    <small class="text-muted">{{ comment.created }}</small>
                    <p>{{ comment.body }}</p>
                </div>
            </div>
        {% endfor %}
    </div>

    <script type="application/javascript">
        function UpdateCode() {
            document.getElementById('sec_code').src = "{{ url_for('main.security_code') }}?s=" + Math.random()
        }
    </script>
{% endblock page_body %}

app/templates/posts/edit.html
{% extends 'base.html' %}
{#{% import 'bootstrap/wtf.html' as wtf %}#}

{% block scripts %}
    {{ super() }}
    {#    {{ pagedown.include_pagedown() }}#}
    {{ pagedown.include_pagedown() }}
{% endblock scripts %}

{% block page_body %}
    <div class="container">
        <div class="container">
            <form method="POST">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    <div>{{ form.title.label }}</div>
                    <div>{{ form.title(class="form-contrl",placeholder=_("请输入文章标题"),required="required") }}</div>
                </div>
                <div class="form-group">
                    <div>{{ form.body.label }}</div>
                    <div>{{ form.body(only_input=True,rows=10,class="form-contrl",required="required") }}</div>
                </div>
                <div>{{ form.body(only_preview=True) }}</div>
                <div class="form-group">
                    {{ form.submit(class="btn btn-primary") }}
                </div>
            </form>
        </div>
    </div>
{% endblock page_body %}

app/templates/register.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert-danger">{{ message }}</div>
        {% endfor %}
        <form method="POST" class="form" role="form">
            {{ form.hidden_tag() }}

            {% if form.errors.username %}
                <div class="form-group has-error required">
                    {{ form.username.label(class="control-label") |safe }}
                    {{ form.username(class="form-control",required=True) }}
                    {% for error in form.errors.username %}
                        <p class="help-block">{{ error }}</p>
                    {% endfor %}
                </div>
            {% else %}
                <div class="form-group required">
                    {{ form.username.label(class="control-label") |safe }}
                    {{ form.username(class="form-control",required=True) }}
                </div>
            {% endif %}


            {% if form.errors.email %}
                <div class="form-group has-error required">
                    {{ form.email.label(class="control-label") |safe }}
                    {{ form.email(class="form-control",required=True) }}
                    {% for error in form.errors.email %}
                        <p class="help-block">{{ error }}</p>
                    {% endfor %}
                </div>
            {% else %}
                <div class="form-group required">
                    {{ form.email.label(class="control-label") |safe }}
                    {{ form.email(class="form-control",required=True) }}
                </div>
            {% endif %}

            {% if form.errors.password %}
                <div class="form-group has-error required">
                    {{ form.password.label(class="control-label") |safe }}
                    {{ form.password(class="form-control",required=True) }}
                    {% for error in form.errors.password %}
                        <p class="help-block">{{ error }}</p>
                    {% endfor %}
                </div>
            {% else %}
                <div class="form-group required">
                    {{ form.password.label(class="control-label") | safe }}
                    {{ form.password(class="form-control", required=True) }}
                </div>
            {% endif %}

            {% if form.errors.password2 %}
                <div class="form-group has-error required">
                    {{ form.password2.label(class="control-label") |safe }}
                    {{ form.password2(class="form-control",required=True) }}
                    {% for error in form.errors.password2 %}
                        <p class="help-block">{{ error }}</p>
                    {% endfor %}
                </div>
            {% else %}
                <div class="form-group required">
                    {{ form.password2.label(class="control-label") | safe }}
                    {{ form.password2(class="form-control", required=True) }}
                </div>
            {% endif %}

            {% if form.errors.verification_code %}
                <div class="form-group has-error required">
                    {{ form.verification_code.label(class="control-label") | safe }}
                    {{ form.verification_code(size=5,maxlength=4, required=True) }}
                    <img src="{{ url_for("auth.get_code") }}" id="get_code">
                    <label class="control-label">
                        <small>{{ _('看不清？点击') }}<a href="javascript:void(0)"
                                                   onclick="RefreshCode()">{{ _('刷新') }}</a></small>
                    </label>
                    {% for error in form.errors.verification_code %}
                        <p class="help-block">{{ error }}</p>
                    {% endfor %}
                </div>
            {% else %}
                <div class="form-group required ">
                    {{ form.verification_code.label(class="control-label")|safe }}
                    {{ form.verification_code(size=5,maxlength=4, required=True) }}
                    <img src="{{ url_for("auth.get_code") }}" id="get_code">
                    <label class="control-label">
                        <small>{{ _('看不清？点击') }}<a href="javascript:void(0)"
                                                   onclick="RefreshCode()">{{ _('刷新') }}</a></small>
                    </label>
                </div>
            {% endif %}
            <div class="form-group required">
                {{ form.submit(class="btn btn-info submit",type='submit') }}
            </div>
        </form>
        <div class="register">
            <a type="button" class="btn btn-info" style="width: 100%;"
               href="{{ url_for("auth.login") }}">{{ _("已有账号？登录") }}</a>
        </div>
    </div>
{% endblock content %}
{% block scripts %}
    {{ super() }}
    <script type="application/javascript">
        function RefreshCode() {
            document.getElementById('get_code').src = "{{ url_for('auth.get_code') }}?rs=" + Math.random()
        }
    </script>
{% endblock scripts %}